/** Microcopy de la web. Vive en el CMS para que todo el texto sea editable. */

export const textosInterfaz = {
  acciones: {
    conocerMas: 'Conocer más',
    verTodosServicios: 'Ver todos los servicios',
    leerBoletin: 'Leer boletín',
    anterior: 'Anterior',
    siguiente: 'Siguiente',
    buscar: 'Buscar',
    buscarPlaceholder: 'Buscar productos, mercados, boletines…',
    abrirMenu: 'Abrir menú',
    cerrarMenu: 'Cerrar menú',
    cambiarIdioma: 'Cambiar idioma',
    saltarContenido: 'Pasar al contenido principal',
    volverInicio: 'Volver al inicio',
  },
  tablero: {
    mercadoFisicos: 'Mercado de físicos',
    mercadoFinancieros: 'Mercado de financieros',
    colNegocio: 'N° Negocio',
    colProducto: 'Producto',
    colCantidad: 'Cantidad',
    colValor: 'Valor',
    colInstrumento: 'Instrumento',
    colTasa: 'Tasa E.A.',
    numeroOperaciones: 'Número operaciones',
    valorNegociado: 'Valor negociado',
    fechaCierre: 'Fecha del cierre',
  },
  boletines: {
    catBoletinDiario: 'Boletín diario',
    catEstudioEconomico: 'Estudio económico',
    catComunicado: 'Comunicado',
    destacado: 'Destacado',
  },
  acceso: {
    tituloEntrar: 'Acceso a plataformas',
    subtituloEntrar: 'Ingrese con su usuario para entrar al portal de la BMC.',
    tituloRegistro: 'Cree su usuario',
    subtituloRegistro: 'Regístrese para acceder a las plataformas habilitadas.',
    campoNombre: 'Nombre de usuario',
    campoCorreo: 'Correo electrónico',
    campoContrasena: 'Contraseña',
    botonEntrar: 'Entrar',
    botonRegistrar: 'Crear usuario',
    irARegistro: '¿No tiene usuario? Regístrese',
    irAEntrar: '¿Ya tiene usuario? Inicie sesión',
    cerrarSesion: 'Cerrar sesión',
    errorCredenciales: 'No pudimos validar sus datos. Revise el correo y la contraseña.',
    errorRegistro: 'No pudimos crear el usuario. Puede que el correo ya esté registrado.',
    procesando: 'Procesando…',
  },
  portal: {
    titulo: 'Portal de plataformas',
    subtitulo: 'Sus accesos y trámites en un solo lugar.',
    saludo: 'Hola',
    sinComponentes: 'No hay componentes habilitados en este momento.',
    abrir: 'Abrir',
    volverAlSitio: 'Volver al sitio público',
    requiereSesion: 'Requiere sesión',
  },
  pqrsf: {
    titulo: 'Asistente PQRSF',
    subtitulo: 'Radique su petición, queja, reclamo, sugerencia o felicitación.',
    placeholder: 'Escriba su mensaje…',
    enviar: 'Enviar',
    reiniciar: 'Nueva solicitud',
    escribiendo: 'El asistente está escribiendo…',
    radicadoTitulo: 'Solicitud radicada',
    radicadoAviso: 'Guarde este número; con él puede consultar el estado de su caso.',
    errorEnvio: 'No pudimos radicar la solicitud. Intente de nuevo en unos minutos.',
  },
  guionPqrsf: [
    {
      clave: 'saludo',
      mensaje:
        'Hola, soy el asistente de PQRSF de la Bolsa Mercantil de Colombia. Le ayudo a radicar su solicitud en menos de un minuto. ¿De qué se trata? Puede escribirlo con sus palabras.',
    },
    {
      clave: 'tipo',
      mensaje:
        'Para clasificarla bien: ¿es una petición, una queja, un reclamo, una sugerencia o una felicitación?',
    },
    { clave: 'asunto', mensaje: 'Entendido. Resúmalo en una frase corta que sirva de asunto.' },
    {
      clave: 'detalle',
      mensaje:
        'Gracias. Ahora cuénteme el detalle: qué pasó, cuándo y con qué producto o plataforma se relaciona.',
    },
    { clave: 'nombre', mensaje: '¿A nombre de quién radico la solicitud?' },
    { clave: 'correo', mensaje: '¿A qué correo electrónico le enviamos la respuesta?' },
    {
      clave: 'confirmacion',
      mensaje: 'Revise el resumen antes de radicar. Si algo no está bien, escríbame la corrección.',
    },
    {
      clave: 'cierre',
      mensaje:
        'Listo. Su solicitud quedó radicada y el equipo responsable la revisará dentro de los términos de ley.',
    },
    {
      clave: 'noEntendido',
      mensaje: 'No estoy seguro de haberle entendido. ¿Puede decirlo de otra forma?',
    },
  ],
}

export const textosInterfazEn = {
  acciones: {
    conocerMas: 'Learn more',
    verTodosServicios: 'See all services',
    leerBoletin: 'Read bulletin',
    anterior: 'Previous',
    siguiente: 'Next',
    buscar: 'Search',
    buscarPlaceholder: 'Search products, markets, bulletins…',
    abrirMenu: 'Open menu',
    cerrarMenu: 'Close menu',
    cambiarIdioma: 'Change language',
    saltarContenido: 'Skip to main content',
    volverInicio: 'Back to home',
  },
  tablero: {
    mercadoFisicos: 'Physical market',
    mercadoFinancieros: 'Financial market',
    colNegocio: 'Trade no.',
    colProducto: 'Product',
    colCantidad: 'Quantity',
    colValor: 'Value',
    colInstrumento: 'Instrument',
    colTasa: 'Rate (EAR)',
    numeroOperaciones: 'Number of transactions',
    valorNegociado: 'Traded value',
    fechaCierre: 'Session date',
  },
  boletines: {
    catBoletinDiario: 'Daily bulletin',
    catEstudioEconomico: 'Economic study',
    catComunicado: 'Announcement',
    destacado: 'Featured',
  },
  acceso: {
    tituloEntrar: 'Platform access',
    subtituloEntrar: 'Sign in with your user to enter the BMC portal.',
    tituloRegistro: 'Create your user',
    subtituloRegistro: 'Register to access the enabled platforms.',
    campoNombre: 'Username',
    campoCorreo: 'Email address',
    campoContrasena: 'Password',
    botonEntrar: 'Sign in',
    botonRegistrar: 'Create user',
    irARegistro: 'No account yet? Register',
    irAEntrar: 'Already registered? Sign in',
    cerrarSesion: 'Sign out',
    errorCredenciales: 'We could not validate your details. Check the email and password.',
    errorRegistro: 'We could not create the user. The email may already be registered.',
    procesando: 'Processing…',
  },
  portal: {
    titulo: 'Platform portal',
    subtitulo: 'Your access points and filings in one place.',
    saludo: 'Hello',
    sinComponentes: 'No components are enabled right now.',
    abrir: 'Open',
    volverAlSitio: 'Back to the public site',
    requiereSesion: 'Sign-in required',
  },
  pqrsf: {
    titulo: 'PQRSF assistant',
    subtitulo: 'File your request, complaint, claim, suggestion or compliment.',
    placeholder: 'Type your message…',
    enviar: 'Send',
    reiniciar: 'New request',
    escribiendo: 'The assistant is typing…',
    radicadoTitulo: 'Request filed',
    radicadoAviso: 'Keep this number; you can use it to check the status of your case.',
    errorEnvio: 'We could not file the request. Please try again in a few minutes.',
  },
  guionPqrsf: [
    {
      clave: 'saludo',
      mensaje:
        'Hello, I am the PQRSF assistant of the Bolsa Mercantil de Colombia. I will help you file your request in under a minute. What is it about? Tell me in your own words.',
    },
    {
      clave: 'tipo',
      mensaje:
        'To classify it properly: is it a request, a complaint, a claim, a suggestion or a compliment?',
    },
    { clave: 'asunto', mensaje: 'Understood. Sum it up in one short sentence to use as the subject.' },
    {
      clave: 'detalle',
      mensaje:
        'Thank you. Now tell me the details: what happened, when, and which product or platform it relates to.',
    },
    { clave: 'nombre', mensaje: 'Under whose name should I file the request?' },
    { clave: 'correo', mensaje: 'Which email address should we send the answer to?' },
    {
      clave: 'confirmacion',
      mensaje: 'Please review the summary before filing. If anything is off, just type the correction.',
    },
    {
      clave: 'cierre',
      mensaje:
        'Done. Your request has been filed and the responsible team will review it within the legal timeframe.',
    },
    { clave: 'noEntendido', mensaje: 'I am not sure I understood. Could you put it another way?' },
  ],
}
